name: ai_companion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.8
  flutter_dotenv: ^5.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  logging: ^1.2.0
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.3.3
  animated_text_kit: ^4.2.2
  path_provider: ^2.0.5
  google_fonts: ^6.2.1
  lottie: ^3.2.0
  google_sign_in: ^6.2.2
  intl: ^0.20.1
  liquid_swipe: ^3.1.0
  card_swiper: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/images/
      - assets/icons/
      - assets/animation/
      - assets/backgrounds/
      - .env
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
    
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Italic.ttf
          style: italic
          weight: 400