name: ai_companion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.8
  flutter_dotenv: ^5.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  logging: ^1.2.0
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.3.3
  animated_text_kit: ^4.2.2
  path_provider: ^2.0.5
  google_fonts: ^6.2.1
  lottie: ^3.2.0
  google_sign_in: ^6.2.2
  intl: ^0.20.1
  liquid_swipe: ^3.1.0
  card_swiper: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/
      - assets/animation/
      - .env